services:
  hugo:
    image: peaceiris/hugo:latest
    container_name: hugo
    volumes:
      - ./rpm_website:/src

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - '1337:1337'
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./rpm_website/public:/var/www/html