baseURL = 'https://reviewsperminute.simonxix.com/'
languageCode = 'en-gb'
title = 'Reviews Per Minute'
theme = 'yinante'
paginate = 10
summaryLength = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "bw"
    tabWidth = 2

[author]
  name = "Simon Bowie"
  homepage = "https://simonxix.com/"

[params]
mainSections = ["posts"]
headTitle = 'Reviews Per Minute'
description = 'film reviews as long as the films'
footer = 'This website is © 2023 Simon Bowie and is licensed under a Creative Commons Attribution 4.0 International License (CC BY 4.0).'
count = 13362


[[params.links]]
name = "About"
link = "/about"

[[params.links]]
name = "Categories"
link = "/categories"

[[params.links]]
name = "RSS"
link = "/index.xml"
new_tab = true

[[params.links]]
name = "SimonXIX"
link = "https://simonxix.com"
new_tab = true

postHeaderContent = ""
# extraCSSFiles = ["css/foo.css", "css/bar.css"]
extraCSSFiles = []